cookie:
  expiry_days: 30
  key: nda_dashboard_secret_key_2026
  name: nda_auth_cookie

credentials:
  usernames:
    admin:
      email: admin@company.com
      first_name: 관리자
      last_name: ""
      password: $2b$12$kLrvOHsBfuzL5ueeHxIvYera6HGut4h/tZHOxwMogQi15WpNj055q
      roles:
        - admin
