cookie:
  expiry_days: 30
  key: nda_dashboard_secret_key_2026
  name: nda_auth_cookie

credentials:
  usernames:
    admin:
      email: admin@company.com
      first_name: 관리자
      last_name: ""
      password: $2b$12$CgtDlA5gS1OseRBOpMtHQuO7Nce8No9D74vraL8.CW3B.do4HlDXG
      roles:
        - admin
